- src/main/java/com/qa/cinema/persistence/Movie.java
> Changed attributes of movie to match the ERD to give a complete entity

- src/main/java/com/qa/cinema/persistence/User.java
> QC2-13 Completed the User Entity

- src/main/java/com/qa/cinema/rest/MovieEndpoint.java
- src/main/java/com/qa/cinema/service/DBMovieService.java
- src/main/java/com/qa/cinema/service/MapMovieService.java
- src/main/java/com/qa/cinema/service/MovieService.java
> Added services relevant to user story and wrote methods.

- src/main/java/com/qa/cinema/persistence/Showing.java
> QC2-8 Created Showing entity

- src/main/java/com/qa/cinema/persistence/Screen.java
- src/main/java/com/qa/cinema/service/DBScreenService.java
- src/main/java/com/qa/cinema/service/MapScreenService.java
- src/main/java/com/qa/cinema/service/ScreenService.java
> QC2-14 created Screen entity

- src/main/java/com/qa/cinema/persistence/Ticket.java
> QC2-4 Ticket Entity

- src/main/java/com/qa/cinema/persistence/Cinema.java
- src/main/java/com/qa/cinema/rest/CinemaEndpoint.java
- src/main/java/com/qa/cinema/service/CinemaService.java
- src/main/webapp/app/service/dal/cinema.js
Changed my /* comment*/ to be consistent with others
> edited javadoc comments for consistancy

- src/main/java/com/qa/cinema/persistence/Screen.java
- src/main/java/com/qa/cinema/rest/ScreenEndPoint.java
- src/main/webapp/app/service/dal/screen.js
> QC2-44 created dal for screen.js and modified Screen/Endpoint

- src/main/java/com/qa/cinema/persistence/Actor.java
- src/main/java/com/qa/cinema/persistence/Movie.java
- src/main/java/com/qa/cinema/persistence/User.java
- src/main/java/com/qa/cinema/rest/UserEndpoint.java
- src/main/java/com/qa/cinema/service/DBUserService.java
- src/test/java/com/qa/cinema/persistence/MovieTest.java
- src/test/java/com/qa/cinema/persistence/UserTest.java
- src/test/java/com/qa/cinema/rest/MovieEndpointTest.java
- src/test/java/com/qa/cinema/service/DBMovieServiceTest.java
- src/test/java/com/qa/cinema/service/DBUserServiceTest.java
- src/test/java/com/qa/cinema/util/JSONUtilTest.java
> QC2 34 - Fixed my updateUser to work correctly now all CRUD opperations work in postman for user

- src/main/java/com/qa/cinema/persistence/Cinema.java
- src/main/java/com/qa/cinema/persistence/Screen.java
Edited column joins on Screen and Cinema
> QC-12 edited column joins

- src/main/webapp/app/service/dal/user.js
> QC2-43 Created user.js (user DAL)

- src/main/java/com/qa/cinema/service/DBShowingService.java
- src/main/java/com/qa/cinema/service/MapShowingService.java
- src/main/java/com/qa/cinema/service/ShowingService.java
> QC2-15 Created Showing service, Map showing service, Showing service

- src/main/webapp/app/app-state-manager.js
- src/main/webapp/index.html
> updated home page and app-state manager to function as currently intended

- src/main/webapp/app/feature/screen/get/get-all-screens-by-cinema/get-screen-by-cinema-controller.js
- src/main/webapp/app/feature/screen/get/get-all-screens-by-cinema/get-screen-by-cinema.html
- src/main/webapp/index.html
> QC2-51 written basic view for screen and added script to index

- src/main/webapp/app/feature/home/home-controller.js
- src/main/webapp/app/feature/home/home.html
- src/main/webapp/app/feature/home/home.js
- src/main/webapp/index.html
> Added carousel taking movies from the db to the homepage

- src/main/webapp/app/feature/cinema/get-cinema/get-all-cinemas/get-all-cinemas-controller.js
RENAMED moviecontroller to cinema controller
> edited cinema controller due to misnamed variable

- src/main/webapp/app/feature/user/add-user/add-user-controller.js
- src/main/webapp/app/feature/user/add-user/add-user.html
html has been updated to have a section for those who already have an account to log in and added columns from bootstrap
> QC2-50 Fixed Movie remnants and updated the html 

- src/main/java/com/qa/cinema/rest/ShowingEndpoint.java
- src/main/java/com/qa/cinema/service/DBShowingService.java
- src/main/java/com/qa/cinema/service/MapShowingService.java
- src/main/java/com/qa/cinema/service/ShowingService.java
> QC2-22 Created ShowingEndpoint class

- src/main/java/com/qa/cinema/service/DBUserService.java
> QC2-83 added unique email check to user creation

- src/main/webapp/app/service/dal/showing.js
> QC2-38 Created dal file for Showing entity

- src/main/webapp/index.html
> Made improvements to the navbar

- src/main/webapp/app/app-state-manager.js
- src/main/webapp/app/feature/cinema/get-cinema/get-all-cinemas/get-all-cinemas-controller.js
- src/main/webapp/app/feature/movie/get/get-one/get-one-movie-controller.js
- src/main/webapp/app/feature/movie/get/get-one/get-one-movie.html
- src/main/webapp/app/service/dal/movie.js
- src/main/webapp/index.html
> Qc2 78 - showing information for a movie can now display

- src/main/webapp/app/app-state-manager.js
- src/main/webapp/app/feature/ticket/add-ticket/add-ticket-controller.js
- src/main/webapp/app/feature/ticket/add-ticket/add-ticket.html
- src/main/webapp/app/service/dal/ticket.js
- src/main/webapp/index.html
> QC2-18 createTicket view

- src/main/webapp/app/app-state-manager.js
- src/main/webapp/app/feature/ticket/get/get-specific-ticket/get-specific-ticket-controller.js
- src/main/webapp/app/feature/ticket/get/get-specific-ticket/get-specific-ticket.html
- src/main/webapp/app/feature/ticket/get/get-ticket-by-showing/get-ticket-by-showing-controller.js
- src/main/webapp/app/feature/ticket/get/get-ticket-by-showing/get-ticket-by-showing.html
- src/main/webapp/app/feature/ticket/get/get-ticket-by-user/get-ticket-by-user-controller.js
- src/main/webapp/app/feature/ticket/get/get-ticket-by-user/get-ticket-by-user.html
- src/main/webapp/index.html
> QC12-18 getticketcontrollers

- src/test/java/com/qa/cinema/service/DBMovieServiceTest.java
> Corrected mockito test to function properly

- src/test/java/com/qa/cinema/service/DBActorServiceTest.java
- src/test/java/com/qa/cinema/service/DBCinemaServiceTest.java
- src/test/java/com/qa/cinema/service/DBMovieServiceTest.java
> Added mockito tests for cinema and actor service classes

- src/test/java/com/qa/cinema/rest/ShowingEndPointTest.java
> QC2-99 Created ShowingEndPointTest

- src/main/webapp/app/feature/user/add-user/add-user-controller.js
A cookie is created when a new user is made; this runs a hashcode-like function on the users email (unique) to generate a random number and stores this on a cookie.
Hash code now users email+password to prevent cookie spoofing by calling the hash function on an email.
> QC2-86 a unique cookie is generated when a user is created

- src/main/webapp/app/feature/user/add-user/add-user-controller.js
> QC2-86 hopefully improving code rating

- src/main/webapp/app/feature/ticket/add-ticket/add-ticket-controller.js
> Removed bug reported by sonarqube

- src/test/java/com/qa/cinema/rest/ScreenEndPointTest.java
> QC2-100 Created and run ScreenEndPointTest

- src/main/webapp/app/feature/user/add-user/add-user-controller.js
using 32 bit in as cookie data
> QC2-86 converted has to 32bit int

- src/main/webapp/app/feature/movie/get/get-current-movies/get-current-movies.css
- src/main/webapp/app/feature/movie/get/get-current-movies/get-current-movies.html
- src/main/webapp/index.css
- src/main/webapp/index.html
> Updated style of currently showing page

- src/main/java/com/qa/cinema/rest/UserEndpoint.java
- src/main/java/com/qa/cinema/service/DBUserService.java
- src/main/java/com/qa/cinema/service/UserService.java
- src/main/webapp/app/feature/ticket/add-ticket/add-ticket-controller.js
- src/main/webapp/app/feature/ticket/add-ticket/add-ticket.html
- src/main/webapp/app/service/dal/user.js
> QC2-48 added get function to get user by email

- src/test/java/com/qa/cinema/rest/CinemaEndpointTest.java
> QC2-102 Created CinemaEndpointTest

- src/main/java/com/qa/cinema/rest/TicketEndpoint.java
- src/main/java/com/qa/cinema/service/DBTicketService.java
- src/main/java/com/qa/cinema/service/TicketService.java
- src/test/java/com/qa/cinema/service/DBTicketServiceTest.java
> Updated the persist ticket method so that multiple tickets may be taken

- src/main/java/com/qa/cinema/service/DBTicketService.java
- src/test/java/com/qa/cinema/service/DBTicketServiceTest.java
> fixed tests to fix build

- src/main/java/com/qa/cinema/service/DBTicketService.java
- src/main/java/com/qa/cinema/util/JSONUtil.java
- src/test/java/com/qa/cinema/service/DBTicketServiceTest.java
- src/test/java/com/qa/cinema/util/JSONUtilTest.java
> Moved method handling JSON to JSON Util and updated tests accordingly

- src/main/java/com/qa/cinema/rest/UserEndpoint.java
- src/main/java/com/qa/cinema/service/DBUserService.java
- src/main/java/com/qa/cinema/service/UserService.java
- src/main/webapp/app/feature/user/add-user/add-user-controller.js
- src/main/webapp/app/feature/user/add-user/add-user.html
- src/main/webapp/app/service/dal/user.js
- src/main/webapp/app/service/factory/userFactory.js
- src/main/webapp/index-controller.js
- src/main/webapp/index.html
Login works login object still displays on login page
> QC2-6 log in works to generate cookie and factory creates an object

- src/main/java/com/qa/cinema/service/DBTicketService.java
- src/test/java/com/qa/cinema/service/DBTicketServiceTest.java
> actually removed number of seats from available seats

- src/main/webapp/app/feature/home/home.html
- src/main/webapp/app/feature/movie/get/get-current-movies/get-current-movies.css
- src/main/webapp/app/feature/movie/get/get-one/get-one-movie.html
> QC2-109 made minor css changes and fixed home page syntax error

- src/main/webapp/app/feature/ticket/add-ticket/add-ticket-controller.js
- src/main/webapp/app/feature/ticket/add-ticket/add-ticket.html
- src/main/webapp/app/feature/ticket/create-booking/create-booking.html
- src/main/webapp/app/service/factory/ticketFactory.js
> Fixed FireFox compatability issue

- src/main/java/com/qa/cinema/rest/UserEndpoint.java
- src/main/java/com/qa/cinema/service/DBUserService.java
- src/main/java/com/qa/cinema/service/UserService.java
- src/main/webapp/app/feature/ticket/create-booking/create-booking-controller.js
- src/main/webapp/app/service/dal/user.js
> QC2-110 fixed findUserIdByEmail after it was removed

- src/main/java/com/qa/cinema/service/DBTicketService.java
- src/main/java/com/qa/cinema/util/JSONUtil.java
- src/test/java/com/qa/cinema/service/DBTicketServiceTest.java
- src/test/java/com/qa/cinema/util/JSONUtilTest.java
> Made ticket service work as intended

- src/main/webapp/app/feature/ticket/add-ticket/add-ticket.html
- src/main/webapp/index.css
> QC2-109 minor css changes

- src/main/webapp/index.css
> Changed navbar to be always at the bottom of page

- src/main/java/com/qa/cinema/service/DBUserService.java
- src/main/webapp/app/feature/user/add-user/add-user-controller.js
> QC2-81 Fixed login hash problem

- src/main/webapp/index.css
> more marginal index.css changes

- src/main/webapp/app/feature/ticket/add-ticket/add-ticket.html
- src/main/webapp/app/feature/user/add-user/add-user.html
> QC2-57 Removed objects for sprint review

- src/main/webapp/app/feature/user/add-user/add-user-controller.js
- src/main/webapp/app/feature/user/add-user/add-user.html
- src/main/webapp/app/service/factory/userFactory.js
A function has been added to the user factory, and can be called to return true/false depending of if the user is logged in.
This has been tested and I have been able to display content only to a user that is logged. 
<div ng-if=ctrl.isLoggedIn() === true> Anything in this is only displayed if the user is logged in </div>
> QC2-112 added a function to check if user is logged in

- src/main/webapp/app/feature/movie/get/get-current-movies/get-current-movies.css
- src/main/webapp/app/feature/movie/get/get-one/get-one-movie.css
- src/main/webapp/app/feature/movie/get/get-one/get-one-movie.html
- src/main/webapp/index.html
> Added some css changes to ensure that the site looks ok on mobile

- src/main/webapp/app/feature/movie/get/get-current-movies/get-current-movies-controller.js
- src/main/webapp/app/feature/movie/get/get-current-movies/get-current-movies.html
- src/main/webapp/app/feature/movie/get/get-one/get-one-movie-controller.js
- src/main/webapp/app/feature/movie/get/get-one/get-one-movie.html
- src/main/webapp/app/feature/ticket/create-booking/create-booking-controller.js
- src/main/webapp/app/feature/ticket/create-booking/create-booking.html
> Link movie showing to booking

- src/main/java/com/qa/cinema/persistence/Offer.java
> QC2-147 Created Offer entity

- src/main/webapp/app/feature/movie/get/get-current-movies/get-current-movies.css
- src/main/webapp/app/feature/movie/get/get-current-movies/get-current-movies.html
- src/main/webapp/app/feature/movie/get/get-one/get-one-movie.css
- src/main/webapp/app/feature/movie/get/get-one/get-one-movie.html
> Made showings with no seats not clickable and greyed out

- src/main/java/com/qa/cinema/rest/OfferEndpoint.java
- src/main/java/com/qa/cinema/service/OfferService.java
> QC2-147 Made OfferEndpoing and Offer Service

- src/main/webapp/app/feature/home/home.css
- src/main/webapp/app/feature/home/home.html
- src/main/webapp/app/feature/user/add-user/add-user-controller.js
- src/main/webapp/app/feature/user/add-user/add-user.html
- src/main/webapp/app/service/factory/userFactory.js
- src/main/webapp/index-controller.js
- src/main/webapp/index.html
> Qc2 150 Added logout function and changed home layout

- src/test/java/com/qa/cinema/service/DBPriceServiceTest.java
- src/test/java/com/qa/cinema/service/DBTicketServiceTest.java
- src/test/java/com/qa/cinema/service/DBUserServiceTest.java
> QC2 148 - Tests for user, ticket and price DB Services

- src/main/webapp/app/feature/ticket/create-booking/create-booking-controller.js
- src/main/webapp/app/feature/ticket/create-booking/create-booking.html
- src/main/webapp/index.css
> QC2-147 Fixed problem with multiple codes

- src/test/java/com/qa/cinema/rest/MovieEndpointTest.java
- src/test/java/com/qa/cinema/rest/PriceEndpointTest.java
- src/test/java/com/qa/cinema/rest/UserEndpointTest.java
> QC2-149 User , Movie and Price Endpoint Tests

- src/test/java/com/qa/cinema/persistence/OfferTest.java
- src/test/java/com/qa/cinema/rest/OfferEndpointTest.java
- src/test/java/com/qa/cinema/service/DBOfferServiceTest.java
> QC2-152 added offer tests

- src/main/webapp/app/feature/home/home-controller.js
- src/main/webapp/index.html
> QC2-112 fixed bug where logged in users couldnt book off of home page

- src/main/webapp/index-controller.js
- src/main/webapp/index.css
- src/main/webapp/index.html
> Added modal instead of warning for cookies and displayed city.

- src/main/webapp/index.html
> QC2-150-2 changed column sizes in index

- src/main/webapp/app/app-state-manager.js
- src/main/webapp/app/feature/classifications/classifications.css
- src/main/webapp/app/feature/classifications/classifications.html
- src/main/webapp/index.css
- src/main/webapp/index.html
> Tidied up navbar cinema features and added a classifications page

- src/main/webapp/app/feature/classifications/classifications.html
> Qc2 151 2 minor changes to classifications page

- src/main/webapp/app/feature/aboutus/aboutus.html
> Replaced image on about us so that it is faster to load

- src/main/webapp/app/feature/ticket/create-booking/create-booking-controller.js
- src/main/webapp/app/feature/ticket/create-booking/create-booking.css
- src/main/webapp/app/feature/ticket/create-booking/create-booking.html
- src/main/webapp/app/feature/user/add-user/add-user-controller.js
- src/main/webapp/app/feature/user/add-user/add-user.html
> Added a number of modals to help clarify certain situations for the user
